### ISSUE TITLE
Dashboard Does not cluster

### ISSUE THREAD

**Issue by JochemZ** [nabeel-qlik/qlik-py-tools#3]
SSE is working, capabilities are shown, but when i open dashboard there is no clustering of data, tried on server and desktop, both the same

**Comment by nabeel-qlik** [comment]
@JochemZ Are you using the sample app? And what exactly is the error you are getting?

You may want to double check that Qlik really recognizes the SSE. If PyTools appears as a known keyword (in blue) as shown below and you see the list of functions when you type `PyTools.` in the editor, we can confirm that the connection is working. 

![pytools connectivity test](https://user-images.githubusercontent.com/21298843/40519394-a19debf6-6002-11e8-9bda-acef6061de65.png)

If that is fine, you can try adding the `debug=true` argument to the clustering expression and check the output in the SSE terminal.

**Comment by JochemZ** [comment]
it is working now, I had the wrong name (port was correct) in the settings.ini

**Comment by nabeel-qlik** [comment]
Great, glad you have it working.
