### ISSUE TITLE
Not getting prediction

### ISSUE THREAD

**Issue by kolbrant** [nabeel-qlik/qlik-py-tools#4]
Hello!

Hoping you can help me sort this issue out:
Was trying this implementation and got it workign with the sample databooks provided with predictions as it should [as shown here](https://gyazo.com/e08206eaf3b09ee22fa5b6d119911728). And the console (Qlik-Py-Start.bat) is putting out some form of output [as shown here](https://gyazo.com/d7fb8aaf440009a04d92ecc821432432).

However, when I try do to it with my own data it doesn't put anything at all to the console and the linegraph in Qlik Sense Desktop (QSD) is just a straight line instead of looking like an actual line [which is shown here](https://gyazo.com/b8069dabeedbe25d7b59647e7cf0f597). 

I have used the same expression and variables as used in the samplebooks provided and changed the parameters to match the name of those in my datasource.

There must then be some kind of issue with the SSE connection to my workbook since nothing is happening with my prediction-line?

Best Regards

**Comment by nabeel-qlik** [comment]
Hi @kolbrant, your line chart shows the actual values are being calculated as ~440M for the entire time series. This indicates that the problem lies with your expression or data model. If you're following the forecast calendar script from this project's documentation you need a bit of set analysis for both the actual and the prediction expressions.

Note the set analysis used in the expressions in the sample app:
`Count({$<FORECAST_LINK_TYPE = {'Actual'}>} Distinct ACCIDENT_NO)`

You could have a simpler data model where this set analysis is not required. I've set up the model in this way so that the actual dates and forecast dates are two different fields, allowing two different set of selections. This lets us run the forecast on a subset of the actual time series e.g. from 2017-2018, yet still visualize the forecast across a longer period e.g. 2016-2019.

**Comment by nabeel-qlik** [comment]
Closing this issue as it is a problem with the Qlik expression/data model rather than this SSE. You're welcome to comment further if you have a follow up question.

**Comment by kolbrant** [comment]
Hello again Nabeel!
I have this current data model: [https://gyazo.com/d58741c5bd935d0155d13ce0794b5d62](link).

The only one from Forecast Calender I really need is _FORECAST_YEAR_ since I only have a year value from the datascourse being a .xlsx file. 

About it showing the sum of ~440M is when I'm using the following expression for the dimension:

`=if(FORECAST_YEAR <= AddYears(Max(Total([År])), $(vForecastPeriods)), FORECAST_YEAR)`

If I change this to only me [År] (showing all years from 1968 - 2017 I get a normal line chart showing the increase of population [https://gyazo.com/8861e75e0bbee664087fa2fe8306601d](like this). At the end is then where I'd like the prediction-line to continue based on the previous data.

So my guess is that the expression is the thief in this situation, how do you think I have to write the expression to get the line as I'd like it? Or just to get the line in general (start at 1968) would also be much appriciated!

Best Regards,
Oskar

**Comment by kolbrant** [comment]
The expression for the Actual and Forecast are as follows - 
Actual: `Sum([Invånare])`
Forecast: `PyTools.Prophet(if(FORECAST_YEAR <= AddYears(Max(Total [År]), $(vForecastPeriods)), FORECAST_YEAR),
Count({$<FORECAST_LINK_TYPE = {'Actual'}>} Sum([Invånare])),
'freq=MS, return=yhat')`

I will try with the example that you provided and see what happens. Given that the Forecast measure expression is somewhat correct for the desired outcome.

Most of the data comes from the .xlsx file, there is however another datasource with location polygon data, but that source does not affect the line-chart.

**Comment by nabeel-qlik** [comment]
When using the Forecast Year as the dimension, you will need to add the set analysis to Actual as well. So it should be Actual: `Sum({$<FORECAST_LINK_TYPE = {'Actual'}>} [Invånare])`. 

The second problem is the measure in the Forecast expression. This should be the same as your Actual expression, as that's what you want to use to make predictions. In my sample app the measure is based on a count but in your case it is a sum. 

Finally, note that your data is at an yearly frequency, so you need to set that correctly in the arguments with `freq=Y` as explained [here](https://github.com/nabeel-qlik/qlik-py-tools/blob/master/docs/Prophet.md#additional-parameters).

So Forecast:

`PyTools.Prophet(if(FORECAST_YEAR <= AddYears(Max(Total [År]), $(vForecastPeriods)), FORECAST_YEAR), Sum({$<FORECAST_LINK_TYPE = {'Actual'}>} [Invånare]), 'freq=Y, return=yhat')`

**Comment by narayanankm** [comment]
Getting the below error while running the installation Qlik-Py-Init.bat. 
@nabeel-oz Can you help me on how to fix it ?

ERROR: Complete output from command 'd:\development\adv_analyics\qlik-py-tools-3.9\qlik-py-env\scripts\python.exe' 'd:\development\adv_analyics\qlik-py-tools-3.9\qlik-py-env\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\qlikuser\AppData\Local\Temp\pip-build-env-v7525snk\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy:
  ERROR: Traceback (most recent call last):
    File "C:\Program Files (x86)\Python36-32\lib\runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "C:\Program Files (x86)\Python36-32\lib\runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "d:\development\adv_analyics\qlik-py-tools-3.9\qlik-py-env\lib\site-packages\pip\__main__.py", line 16, in <module>
      from pip._internal import main as _main  # isort:skip # noqa
    File "d:\development\adv_analyics\qlik-py-tools-3.9\qlik-py-env\lib\site-packages\pip\_internal\__init__.py", line 4, in <module>
      import locale
    File "C:\Program Files (x86)\Python36-32\lib\locale.py", line 16, in <module>
      import re
    File "C:\Program Files (x86)\Python36-32\lib\re.py", line 142, in <module>
      class RegexFlag(enum.IntFlag):
  AttributeError: module 'enum' has no attribute 'IntFlag'
  ----------------------------------------
ERROR: Command "'d:\development\adv_analyics\qlik-py-tools-3.9\qlik-py-env\scripts\python.exe' 'd:\development\adv_analyics\qlik-py-tools-3.9\qlik-py-env\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\qlikuser\AppData\Local\Temp\pip-build-env-v7525snk\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy" failed with error code 1 in None_

**Comment by nabeel-oz** [comment]
Hi @narayanankm, that error seems to be with pip which is a very basic module in Python. You'll need to check that your environment is set up correctly according to the installation notes. 

One possible problem is that you're running the 32 bit installation of Python. On a modern system you really should be using the 64 bit version.
